/**
 * 任務模板系統 - 公司維運導向
 * 聚焦企業日常營運任務，讓 AI + 真人協作完成
 */

export interface TaskTemplate {
  id: string;
  name: string;
  nameEn: string;
  icon: string;
  category: "hr" | "finance" | "project" | "admin" | "it" | "custom";
  description: string;
  descriptionEn: string;
  stages: TaskStage[];
  estimatedTime: string;
  outputFormats: ('pdf' | 'ppt' | 'doc' | 'xls')[];
}

export interface TaskStage {
  id: number;
  name: string;
  nameEn: string;
  description: string;
  descriptionEn: string;
  checklist: string[];
  checklistEn: string[];
  assignTo?: "ai" | "human" | "both";
}

export const taskTemplates: TaskTemplate[] = [
  // ===== HR 人資 =====
  {
    id: "employee-onboarding",
    name: "新人入職流程",
    nameEn: "Employee Onboarding",
    icon: "👋",
    category: "hr",
    description: "完整的新員工入職準備和引導流程",
    descriptionEn: "Complete new employee onboarding preparation and guidance",
    estimatedTime: "1-2 days",
    outputFormats: ["pdf", "doc"],
    stages: [
      {
        id: 1,
        name: "入職準備",
        nameEn: "Pre-boarding",
        description: "準備新人所需的帳號、設備和資料",
        descriptionEn: "Prepare accounts, equipment and materials",
        assignTo: "both",
        checklist: ["建立公司帳號", "準備電腦設備", "製作員工證", "準備座位"],
        checklistEn: ["Create company accounts", "Prepare computer", "Make employee ID", "Assign desk"],
      },
      {
        id: 2,
        name: "文件簽署",
        nameEn: "Documentation",
        description: "完成勞動契約和相關文件",
        descriptionEn: "Complete employment contract and documents",
        assignTo: "human",
        checklist: ["勞動契約", "保密協議", "個資同意書", "緊急聯絡人"],
        checklistEn: ["Employment contract", "NDA", "Privacy consent", "Emergency contact"],
      },
      {
        id: 3,
        name: "系統培訓",
        nameEn: "System Training",
        description: "公司系統和工具使用培訓",
        descriptionEn: "Company systems and tools training",
        assignTo: "ai",
        checklist: ["Email/Slack 設定", "專案管理工具", "請假系統", "報銷系統"],
        checklistEn: ["Email/Slack setup", "Project management tools", "Leave system", "Expense system"],
      },
      {
        id: 4,
        name: "團隊介紹",
        nameEn: "Team Introduction",
        description: "安排與團隊成員的認識",
        descriptionEn: "Arrange meetings with team members",
        assignTo: "both",
        checklist: ["直屬主管面談", "團隊成員介紹", "跨部門窗口", "Mentor 指派"],
        checklistEn: ["Manager meeting", "Team introductions", "Cross-dept contacts", "Mentor assignment"],
      },
      {
        id: 5,
        name: "完成確認",
        nameEn: "Completion",
        description: "確認入職流程完成並歸檔",
        descriptionEn: "Confirm completion and archive",
        assignTo: "ai",
        checklist: ["入職清單確認", "試用期目標設定", "30天跟進提醒", "文件歸檔"],
        checklistEn: ["Checklist confirmation", "Probation goals", "30-day follow-up", "Document archiving"],
      },
    ],
  },
  {
    id: "performance-review",
    name: "績效考核",
    nameEn: "Performance Review",
    icon: "📊",
    category: "hr",
    description: "員工績效評估和發展計劃",
    descriptionEn: "Employee performance evaluation and development planning",
    estimatedTime: "2-3 hours",
    outputFormats: ["pdf", "xls"],
    stages: [
      {
        id: 1,
        name: "資料收集",
        nameEn: "Data Collection",
        description: "收集員工績效相關數據",
        descriptionEn: "Collect employee performance data",
        assignTo: "ai",
        checklist: ["KPI 達成率", "專案完成度", "360 度回饋", "出勤記錄"],
        checklistEn: ["KPI achievement", "Project completion", "360 feedback", "Attendance record"],
      },
      {
        id: 2,
        name: "自評填寫",
        nameEn: "Self-Assessment",
        description: "員工完成自我評估",
        descriptionEn: "Employee completes self-assessment",
        assignTo: "human",
        checklist: ["成就描述", "挑戰困難", "學習成長", "下期目標"],
        checklistEn: ["Achievements", "Challenges", "Learning growth", "Next period goals"],
      },
      {
        id: 3,
        name: "主管評估",
        nameEn: "Manager Review",
        description: "主管進行評分和回饋",
        descriptionEn: "Manager scoring and feedback",
        assignTo: "human",
        checklist: ["能力評分", "行為評估", "發展建議", "薪資建議"],
        checklistEn: ["Competency scoring", "Behavior assessment", "Development suggestions", "Salary recommendation"],
      },
      {
        id: 4,
        name: "面談溝通",
        nameEn: "Review Meeting",
        description: "安排主管與員工面談",
        descriptionEn: "Schedule manager-employee meeting",
        assignTo: "both",
        checklist: ["預約時間", "準備議程", "面談記錄", "雙方簽名"],
        checklistEn: ["Schedule time", "Prepare agenda", "Meeting notes", "Both signatures"],
      },
      {
        id: 5,
        name: "結果歸檔",
        nameEn: "Finalization",
        description: "完成評估並歸檔",
        descriptionEn: "Complete and archive evaluation",
        assignTo: "ai",
        checklist: ["報告生成", "HR 系統更新", "通知相關人員", "下期目標設定"],
        checklistEn: ["Report generation", "HR system update", "Notify stakeholders", "Set next goals"],
      },
    ],
  },

  // ===== 財務 Finance =====
  {
    id: "expense-report",
    name: "費用報銷",
    nameEn: "Expense Report",
    icon: "💰",
    category: "finance",
    description: "員工費用報銷申請和審批",
    descriptionEn: "Employee expense claim and approval",
    estimatedTime: "30 mins",
    outputFormats: ["pdf", "xls"],
    stages: [
      {
        id: 1,
        name: "填寫申請",
        nameEn: "Submit Request",
        description: "填寫報銷明細和上傳憑證",
        descriptionEn: "Fill expense details and upload receipts",
        assignTo: "human",
        checklist: ["費用類別", "金額明細", "上傳發票", "備註說明"],
        checklistEn: ["Expense category", "Amount details", "Upload invoice", "Notes"],
      },
      {
        id: 2,
        name: "AI 審核",
        nameEn: "AI Review",
        description: "AI 檢查金額和政策合規",
        descriptionEn: "AI checks amount and policy compliance",
        assignTo: "ai",
        checklist: ["金額核對", "政策檢查", "重複檢測", "異常標記"],
        checklistEn: ["Amount verification", "Policy check", "Duplicate detection", "Flag anomalies"],
      },
      {
        id: 3,
        name: "主管審批",
        nameEn: "Manager Approval",
        description: "直屬主管審批",
        descriptionEn: "Direct manager approval",
        assignTo: "human",
        checklist: ["審核內容", "核准/退回", "批註意見"],
        checklistEn: ["Review content", "Approve/Reject", "Add comments"],
      },
      {
        id: 4,
        name: "財務撥款",
        nameEn: "Finance Processing",
        description: "財務處理付款",
        descriptionEn: "Finance processes payment",
        assignTo: "both",
        checklist: ["款項確認", "銀行轉帳", "記帳登錄"],
        checklistEn: ["Amount confirmation", "Bank transfer", "Accounting entry"],
      },
      {
        id: 5,
        name: "完成通知",
        nameEn: "Completion",
        description: "通知申請人並歸檔",
        descriptionEn: "Notify applicant and archive",
        assignTo: "ai",
        checklist: ["發送通知", "更新狀態", "文件歸檔"],
        checklistEn: ["Send notification", "Update status", "Archive documents"],
      },
    ],
  },
  {
    id: "budget-planning",
    name: "預算編制",
    nameEn: "Budget Planning",
    icon: "📈",
    category: "finance",
    description: "部門或專案預算規劃",
    descriptionEn: "Department or project budget planning",
    estimatedTime: "4-6 hours",
    outputFormats: ["xls", "pdf", "ppt"],
    stages: [
      {
        id: 1,
        name: "歷史分析",
        nameEn: "Historical Analysis",
        description: "AI 分析過去支出模式",
        descriptionEn: "AI analyzes past spending patterns",
        assignTo: "ai",
        checklist: ["去年預算", "實際支出", "差異分析", "趨勢預測"],
        checklistEn: ["Last year budget", "Actual spending", "Variance analysis", "Trend forecast"],
      },
      {
        id: 2,
        name: "需求收集",
        nameEn: "Requirement Gathering",
        description: "收集各單位預算需求",
        descriptionEn: "Collect budget requirements from units",
        assignTo: "both",
        checklist: ["人力成本", "營運費用", "專案投資", "緊急預備"],
        checklistEn: ["Personnel cost", "Operating expenses", "Project investment", "Contingency"],
      },
      {
        id: 3,
        name: "預算編列",
        nameEn: "Budget Draft",
        description: "編制預算草案",
        descriptionEn: "Draft budget proposal",
        assignTo: "both",
        checklist: ["項目分類", "金額分配", "月度分配", "說明備註"],
        checklistEn: ["Item categorization", "Amount allocation", "Monthly breakdown", "Notes"],
      },
      {
        id: 4,
        name: "審核調整",
        nameEn: "Review & Adjust",
        description: "高層審核並調整",
        descriptionEn: "Executive review and adjustment",
        assignTo: "human",
        checklist: ["總額審核", "優先排序", "刪減調整", "最終核准"],
        checklistEn: ["Total review", "Prioritization", "Cuts and adjustments", "Final approval"],
      },
      {
        id: 5,
        name: "發布執行",
        nameEn: "Publication",
        description: "發布預算並設定追蹤",
        descriptionEn: "Publish budget and set tracking",
        assignTo: "ai",
        checklist: ["報告生成", "系統設定", "通知相關人", "追蹤提醒"],
        checklistEn: ["Report generation", "System setup", "Notify stakeholders", "Tracking reminders"],
      },
    ],
  },

  // ===== 專案管理 Project =====
  {
    id: "project-kickoff",
    name: "專案啟動",
    nameEn: "Project Kickoff",
    icon: "🚀",
    category: "project",
    description: "新專案的規劃和啟動流程",
    descriptionEn: "New project planning and kickoff process",
    estimatedTime: "2-4 hours",
    outputFormats: ["pdf", "ppt", "doc"],
    stages: [
      {
        id: 1,
        name: "需求定義",
        nameEn: "Requirements",
        description: "明確專案目標和範圍",
        descriptionEn: "Define project goals and scope",
        assignTo: "both",
        checklist: ["專案目標", "成功指標", "範圍界定", "排除項目"],
        checklistEn: ["Project goals", "Success metrics", "Scope definition", "Exclusions"],
      },
      {
        id: 2,
        name: "資源規劃",
        nameEn: "Resource Planning",
        description: "確定所需人力和資源",
        descriptionEn: "Determine required personnel and resources",
        assignTo: "both",
        checklist: ["團隊組成", "預算估算", "工具需求", "外部資源"],
        checklistEn: ["Team composition", "Budget estimate", "Tool requirements", "External resources"],
      },
      {
        id: 3,
        name: "時程規劃",
        nameEn: "Timeline Planning",
        description: "AI 協助制定專案時程",
        descriptionEn: "AI assists in project timeline",
        assignTo: "ai",
        checklist: ["里程碑設定", "任務分解", "依賴關係", "緩衝時間"],
        checklistEn: ["Milestone setting", "Task breakdown", "Dependencies", "Buffer time"],
      },
      {
        id: 4,
        name: "風險評估",
        nameEn: "Risk Assessment",
        description: "識別和評估潛在風險",
        descriptionEn: "Identify and assess potential risks",
        assignTo: "ai",
        checklist: ["風險識別", "影響評估", "應對策略", "監控機制"],
        checklistEn: ["Risk identification", "Impact assessment", "Mitigation strategies", "Monitoring"],
      },
      {
        id: 5,
        name: "啟動會議",
        nameEn: "Kickoff Meeting",
        description: "召開專案啟動會議",
        descriptionEn: "Hold project kickoff meeting",
        assignTo: "human",
        checklist: ["簡報準備", "會議安排", "紀錄分發", "任務指派"],
        checklistEn: ["Prepare presentation", "Schedule meeting", "Distribute notes", "Assign tasks"],
      },
    ],
  },
  {
    id: "weekly-standup",
    name: "週會管理",
    nameEn: "Weekly Standup",
    icon: "📅",
    category: "project",
    description: "團隊週會準備和追蹤",
    descriptionEn: "Team weekly meeting preparation and follow-up",
    estimatedTime: "1 hour",
    outputFormats: ["pdf", "doc"],
    stages: [
      {
        id: 1,
        name: "進度收集",
        nameEn: "Progress Collection",
        description: "AI 收集各成員本週進度",
        descriptionEn: "AI collects progress from each member",
        assignTo: "ai",
        checklist: ["完成事項", "進行中任務", "遇到問題", "下週計劃"],
        checklistEn: ["Completed items", "In-progress tasks", "Blockers", "Next week plan"],
      },
      {
        id: 2,
        name: "議程準備",
        nameEn: "Agenda Preparation",
        description: "生成會議議程",
        descriptionEn: "Generate meeting agenda",
        assignTo: "ai",
        checklist: ["議程大綱", "討論重點", "決策事項", "時間分配"],
        checklistEn: ["Agenda outline", "Discussion points", "Decisions needed", "Time allocation"],
      },
      {
        id: 3,
        name: "會議進行",
        nameEn: "Meeting",
        description: "召開週會",
        descriptionEn: "Hold weekly meeting",
        assignTo: "human",
        checklist: ["開場", "進度報告", "問題討論", "決策"],
        checklistEn: ["Opening", "Progress reports", "Issue discussion", "Decisions"],
      },
      {
        id: 4,
        name: "紀錄整理",
        nameEn: "Notes Summary",
        description: "AI 整理會議紀錄",
        descriptionEn: "AI summarizes meeting notes",
        assignTo: "ai",
        checklist: ["重點摘要", "決議事項", "待辦事項", "下次議題"],
        checklistEn: ["Key points", "Decisions", "Action items", "Next agenda"],
      },
      {
        id: 5,
        name: "追蹤分派",
        nameEn: "Follow-up",
        description: "分派任務並設定追蹤",
        descriptionEn: "Assign tasks and set follow-ups",
        assignTo: "both",
        checklist: ["任務指派", "截止日期", "提醒設定", "紀錄發送"],
        checklistEn: ["Task assignment", "Deadlines", "Reminder setup", "Send notes"],
      },
    ],
  },

  // ===== 行政 Admin =====
  {
    id: "vendor-management",
    name: "供應商管理",
    nameEn: "Vendor Management",
    icon: "🤝",
    category: "admin",
    description: "供應商評估和合約管理",
    descriptionEn: "Vendor evaluation and contract management",
    estimatedTime: "2-3 hours",
    outputFormats: ["pdf", "xls"],
    stages: [
      {
        id: 1,
        name: "需求確認",
        nameEn: "Requirement",
        description: "確認採購需求和規格",
        descriptionEn: "Confirm procurement requirements",
        assignTo: "human",
        checklist: ["需求說明", "規格要求", "預算範圍", "時程需求"],
        checklistEn: ["Requirement description", "Specifications", "Budget range", "Timeline"],
      },
      {
        id: 2,
        name: "供應商搜尋",
        nameEn: "Vendor Search",
        description: "AI 搜尋和篩選供應商",
        descriptionEn: "AI searches and filters vendors",
        assignTo: "ai",
        checklist: ["市場調查", "供應商清單", "初步篩選", "聯繫資訊"],
        checklistEn: ["Market research", "Vendor list", "Initial filtering", "Contact info"],
      },
      {
        id: 3,
        name: "報價比較",
        nameEn: "Quote Comparison",
        description: "收集報價並比較",
        descriptionEn: "Collect and compare quotes",
        assignTo: "both",
        checklist: ["報價收集", "功能比較", "價格分析", "條款比較"],
        checklistEn: ["Collect quotes", "Feature comparison", "Price analysis", "Terms comparison"],
      },
      {
        id: 4,
        name: "合約審核",
        nameEn: "Contract Review",
        description: "審核合約條款",
        descriptionEn: "Review contract terms",
        assignTo: "human",
        checklist: ["條款審核", "法務確認", "談判協商", "最終確認"],
        checklistEn: ["Terms review", "Legal confirmation", "Negotiation", "Final confirmation"],
      },
      {
        id: 5,
        name: "簽約歸檔",
        nameEn: "Signing & Archive",
        description: "完成簽約並建立檔案",
        descriptionEn: "Complete signing and create records",
        assignTo: "both",
        checklist: ["合約簽署", "付款安排", "聯絡窗口", "到期提醒"],
        checklistEn: ["Contract signing", "Payment arrangement", "Contact person", "Expiry reminder"],
      },
    ],
  },

  // ===== IT =====
  {
    id: "system-incident",
    name: "系統異常處理",
    nameEn: "System Incident",
    icon: "🔧",
    category: "it",
    description: "系統問題的通報和處理流程",
    descriptionEn: "System issue reporting and resolution",
    estimatedTime: "Varies",
    outputFormats: ["pdf", "doc"],
    stages: [
      {
        id: 1,
        name: "問題通報",
        nameEn: "Incident Report",
        description: "記錄問題詳情",
        descriptionEn: "Record issue details",
        assignTo: "human",
        checklist: ["問題描述", "影響範圍", "發生時間", "截圖/日誌"],
        checklistEn: ["Issue description", "Impact scope", "Occurrence time", "Screenshots/Logs"],
      },
      {
        id: 2,
        name: "初步診斷",
        nameEn: "Initial Diagnosis",
        description: "AI 分析可能原因",
        descriptionEn: "AI analyzes possible causes",
        assignTo: "ai",
        checklist: ["日誌分析", "相似案例", "可能原因", "建議方案"],
        checklistEn: ["Log analysis", "Similar cases", "Possible causes", "Suggested solutions"],
      },
      {
        id: 3,
        name: "問題處理",
        nameEn: "Resolution",
        description: "執行修復方案",
        descriptionEn: "Execute fix",
        assignTo: "both",
        checklist: ["方案執行", "測試驗證", "回滾準備", "狀態更新"],
        checklistEn: ["Execute solution", "Test verification", "Rollback ready", "Status update"],
      },
      {
        id: 4,
        name: "通知相關人",
        nameEn: "Notification",
        description: "更新狀態並通知",
        descriptionEn: "Update status and notify",
        assignTo: "ai",
        checklist: ["內部通知", "用戶通知", "狀態更新", "進度報告"],
        checklistEn: ["Internal notification", "User notification", "Status update", "Progress report"],
      },
      {
        id: 5,
        name: "事後檢討",
        nameEn: "Post-mortem",
        description: "記錄經驗和改進措施",
        descriptionEn: "Document lessons and improvements",
        assignTo: "both",
        checklist: ["根因分析", "經驗教訓", "改進措施", "文件歸檔"],
        checklistEn: ["Root cause analysis", "Lessons learned", "Improvements", "Documentation"],
      },
    ],
  },

  // ===== 自訂 Custom =====
  {
    id: "custom",
    name: "自訂流程",
    nameEn: "Custom Workflow",
    icon: "✨",
    category: "custom",
    description: "建立自訂的工作流程",
    descriptionEn: "Create custom workflow",
    estimatedTime: "Varies",
    outputFormats: ["pdf", "ppt", "doc", "xls"],
    stages: [
      {
        id: 1,
        name: "定義任務",
        nameEn: "Define Task",
        description: "描述你要完成的任務",
        descriptionEn: "Describe the task you want to complete",
        assignTo: "human",
        checklist: ["任務目標", "預期產出", "相關人員", "時間限制"],
        checklistEn: ["Task goal", "Expected output", "Stakeholders", "Time limit"],
      },
      {
        id: 2,
        name: "AI 規劃",
        nameEn: "AI Planning",
        description: "AI 建議執行步驟",
        descriptionEn: "AI suggests execution steps",
        assignTo: "ai",
        checklist: ["步驟拆解", "資源需求", "風險評估", "時程建議"],
        checklistEn: ["Step breakdown", "Resource needs", "Risk assessment", "Timeline suggestion"],
      },
      {
        id: 3,
        name: "執行任務",
        nameEn: "Execute Task",
        description: "按步驟完成任務",
        descriptionEn: "Complete task step by step",
        assignTo: "both",
        checklist: ["進度追蹤", "問題回報", "調整計劃", "協作確認"],
        checklistEn: ["Progress tracking", "Issue reporting", "Adjust plan", "Collaboration check"],
      },
      {
        id: 4,
        name: "審核產出",
        nameEn: "Review Output",
        description: "審核任務成果",
        descriptionEn: "Review task deliverables",
        assignTo: "human",
        checklist: ["品質檢查", "修改建議", "相關人確認", "最終核准"],
        checklistEn: ["Quality check", "Revision suggestions", "Stakeholder approval", "Final sign-off"],
      },
      {
        id: 5,
        name: "完成交付",
        nameEn: "Complete & Deliver",
        description: "完成任務並交付成果",
        descriptionEn: "Complete task and deliver results",
        assignTo: "ai",
        checklist: ["格式選擇", "導出檔案", "通知相關人", "歸檔紀錄"],
        checklistEn: ["Format selection", "Export file", "Notify stakeholders", "Archive record"],
      },
    ],
  },
];

export const categoryLabels = {
  hr: { zh: "人資", en: "HR" },
  finance: { zh: "財務", en: "Finance" },
  project: { zh: "專案", en: "Project" },
  admin: { zh: "行政", en: "Admin" },
  it: { zh: "IT", en: "IT" },
  custom: { zh: "自訂", en: "Custom" },
};

export default taskTemplates;
